services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./symfony:/var/www/symfony
    working_dir: /var/www/symfony
    command: php-fpm
    depends_on:
      - db
      - freeswitch
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - appnet

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: testapiw@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123 
    ports:
      - "8081:80"  # docker compose up -d pgadmin http://localhost:8081
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  # docker exec -it freeswitch fs_cli
  freeswitch:
    build:
      context: .
      dockerfile: docker/freeswitch/Dockerfile
    volumes:
      - ./docker/freeswitch/conf:/usr/local/freeswitch/conf
      - ./docker/freeswitch/log:/usr/local/freeswitch/log
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5080:5080"
      - "8021:8021"
    networks:
      - appnet


volumes:
  pgadmin_data:

networks:
  appnet:
    driver: bridge